Update update.yml

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -22,7 +22,7 @@ jobs:
         run: pip install -r requirements.txt
 
       - name: Run DB builder
-        run: python build_db_app.py
+        run: python build_db_app.py || echo "build failed"
 
       - name: Commit changes
         run: |
